### ISSUE TITLE
获取wss那一步失败了

### ISSUE THREAD

**Issue by zhangxiangfeng** [banyin-lx/DouYinFetch#1]
应该是抖音增加判断人机判断机制了。

**Comment by banyin-lx** [comment]
后续会改成selenium后台打开浏览器通过代理获取数据包

**Comment by Are-sky** [comment]
当我修改了sid_tt后，就可以成功获取到wss链接了

**Comment by Are-sky** [comment]
> 当我修改了sid_tt后，就可以成功获取到wss链接了

sid_tt可能是一个敏感的客户端id，这个应该由使用者自行配置

**Comment by tscrtxdy** [comment]
运行报错：While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

**Comment by zhangziliang04** [comment]
> 

遇到了同样的问题。不知道如何处理？目前是否有答案了。

**Comment by zhangziliang04** [comment]
> 当我修改了sid_tt后，就可以成功获取到wss链接了

请问是如何修改的？

**Comment by tscrtxdy** [comment]
> > 
> 
> 遇到了同样的问题。不知道如何处理？目前是否有答案了。

没解决。也不知道到底是什么原因

**Comment by tscrtxdy** [comment]
> > 当我修改了sid_tt后，就可以成功获取到wss链接了
> 
> sid_tt可能是一个敏感的客户端id，这个应该由使用者自行配置

请问是修改成什么值，我随便修改后，还是会报错

**Comment by tscrtxdy** [comment]
> 后续会改成selenium后台打开浏览器通过代理获取数据包

为什么我运行报错：While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

**Comment by tscrtxdy** [comment]
> 后续会改成selenium后台打开浏览器通过代理获取数据包

报错堆栈
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1259)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:910)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:513)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:490)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:603)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:303)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:833)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:517)
	at com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(GeneratedMessageV3.java:865)
	at entity.protobuf.DouYinHeader$Response$Builder.mergeFrom(DouYinHeader.java:3292)
	at entity.protobuf.DouYinHeader$Response$1.parsePartialFrom(DouYinHeader.java:4229)
	at entity.protobuf.DouYinHeader$Response$1.parsePartialFrom(DouYinHeader.java:4221)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at entity.protobuf.DouYinHeader$Response.parseFrom(DouYinHeader.java:2890)
	at com.dy.douyinfetch.service.FetchDouYin.getWssUrl(FetchDouYin.java:226)
	at com.dy.douyinfetch.service.FetchDouYin.startListening(FetchDouYin.java:79)
	at com.dy.douyinfetch.DouYinFetchApplication.main(DouYinFetchApplication.java:16)

**Comment by Are-sky** [comment]
> 

不能随便修改 可以改成自己在抖音网页中的对应cookie值

**Comment by tscrtxdy** [comment]
> > 
> 
> 不能随便修改 可以改成自己在抖音网页中的对应cookie值

如果我要是实际项目中使用，总不能写死吧，这个应该如何处理呢？

**Comment by Are-sky** [comment]
> > > 
> > 
> > 
> > 不能随便修改 可以改成自己在抖音网页中的对应cookie值
> 
> 如果我要是实际项目中使用，总不能写死吧，这个应该如何处理呢？

那就动态获取咯

**Comment by tscrtxdy** [comment]
> > > > 
> > > 
> > > 
> > > 不能随便修改 可以改成自己在抖音网页中的对应cookie值
> > 
> > 
> > 如果我要是实际项目中使用，总不能写死吧，这个应该如何处理呢？
> 
> 那就动态获取咯
具体怎么做，不是很懂。可以提供代码不
